/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a user
         * @description Admins and sales managers.
         */
        get: operations["get"];
        /**
         * Update a user
         * @description Admins only. Changing role or deactivating ends the user's sessions.
         */
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sales-reps/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a sales rep
         * @description Reps may only open their own profile.
         */
        get: operations["get_1"];
        /**
         * Update a sales profile
         * @description Managers and admins: title, territory, quota…
         */
        put: operations["update_1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an opportunity, with its stage history */
        get: operations["get_2"];
        /**
         * Update an opportunity
         * @description Owner, managers and admins. Requires the loaded version.
         */
        put: operations["update_2"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a contact */
        get: operations["get_3"];
        /**
         * Update a contact
         * @description Owner, managers and admins. Requires the loaded version.
         */
        put: operations["update_3"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change your password
         * @description Signs you out of every other session.
         */
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an account */
        get: operations["get_4"];
        /**
         * Update an account
         * @description Owner, managers and admins. Requires the loaded version.
         */
        put: operations["update_4"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Admins and sales managers.
         */
        get: operations["list"];
        put?: never;
        /**
         * Create a user
         * @description Admins only. The initial password is shared out of band.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sales-reps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sales reps with performance figures
         * @description Managers and admins see the whole team; reps see only themselves.
         */
        get: operations["list_1"];
        put?: never;
        /**
         * Create a sales rep
         * @description Admins only. Creates the sign-in account and profile.
         */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List opportunities
         * @description Reps see only their own opportunities.
         */
        get: operations["list_2"];
        put?: never;
        /** Create an opportunity */
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{id}/stage-transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move an opportunity to another stage
         * @description The pipeline workflow: one stage at a time forwards or back, won only from Negotiation, lost from any open stage, closed deals reopen into any open stage. Resets the probability to the stage default and records stage history, an audit event and a timeline activity. 409 INVALID_STATE_TRANSITION for a move the workflow doesn't allow, 409 CONFLICT for a stale version.
         */
        post: operations["transition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore an archived opportunity
         * @description Managers and admins.
         */
        post: operations["restore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive an opportunity
         * @description Managers and admins.
         */
        post: operations["archive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List leads
         * @description Paginated, searchable list of active (non-archived) leads.
         */
        get: operations["list_3"];
        put?: never;
        /** Create a lead */
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{id}/status-transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change a lead's status
         * @description Between NEW, CONTACTED, QUALIFIED and DISQUALIFIED. Converted leads never change (409 ALREADY_CONVERTED). Records an audit event and a timeline activity.
         */
        post: operations["changeStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{id}/conversion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Convert a qualified lead
         * @description Creates (or links) the account, creates the contact and the opportunity, and marks the lead CONVERTED — all in one transaction. 409 ALREADY_CONVERTED on a second attempt, 409 INVALID_STATE_TRANSITION if the lead isn't qualified, 409 CONFLICT for a stale version.
         */
        post: operations["convert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List contacts
         * @description Every signed-in user can browse contacts.
         */
        get: operations["list_4"];
        put?: never;
        /** Create a contact */
        post: operations["create_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore an archived contact
         * @description Managers and admins.
         */
        post: operations["restore_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive a contact
         * @description Managers and admins. An archived contact stops being primary.
         */
        post: operations["archive_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Starts a server-side session (PARALLAX_SESSION cookie).
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A record's activity timeline
         * @description Newest first. Give exactly one of leadId, accountId, contactId or opportunityId; you see the timeline of any record you can open.
         */
        get: operations["timeline"];
        put?: never;
        /**
         * Log a call, email, meeting or note
         * @description On a lead or opportunity you can work on, or on any active account or contact.
         */
        post: operations["log"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List accounts
         * @description Every signed-in user can browse accounts.
         */
        get: operations["list_5"];
        put?: never;
        /** Create an account */
        post: operations["create_5"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore an archived account
         * @description Managers and admins.
         */
        post: operations["restore_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive an account
         * @description Managers and admins.
         */
        post: operations["archive_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The pipeline board
         * @description One column per stage with its count, amount and weighted amount, plus the cards to show. Covers active opportunities you can see (reps: their own).
         */
        get: operations["board"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{id}/stage-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every stage the opportunity entered, oldest first */
        get: operations["stageHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pipeline totals
         * @description Open, weighted and won totals over the opportunities you can see (reps: their own).
         */
        get: operations["summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a lead */
        get: operations["get_5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user and their permissions */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Issue a CSRF token
         * @description Sets the XSRF-TOKEN cookie. Send its value in the X-XSRF-TOKEN header on every write request.
         */
        get: operations["csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateUserRequest: {
            firstName: string;
            lastName: string;
            /** @enum {string} */
            role: "ADMIN" | "SALES_MANAGER" | "SALES_REP";
            active: boolean;
            /** Format: int64 */
            version: number;
        };
        UserResponse: {
            /** Format: uuid */
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            fullName: string;
            /** @enum {string} */
            role: "ADMIN" | "SALES_MANAGER" | "SALES_REP";
            active: boolean;
            /** Format: date-time */
            lastLoginAt?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: int64 */
            version: number;
        };
        SalesProfileRequest: {
            title?: string;
            department?: string;
            phone?: string;
            territory?: string;
            quota: number;
            /**
             * Format: int64
             * @description profileVersion from the loaded rep (0 if they have no profile yet).
             */
            version: number;
        };
        SalesRepResponse: {
            /** Format: uuid */
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            fullName: string;
            /** @enum {string} */
            role: "ADMIN" | "SALES_MANAGER" | "SALES_REP";
            active: boolean;
            title?: string;
            department?: string;
            phone?: string;
            territory?: string;
            quota: number;
            ytdSales: number;
            attainmentPercent?: number;
            /** Format: int64 */
            openLeadCount: number;
            /** Format: int64 */
            accountCount: number;
            /** Format: int64 */
            openOpportunityCount: number;
            openPipeline: number;
            weightedPipeline: number;
            /** Format: int64 */
            profileVersion: number;
            canEdit: boolean;
        };
        OpportunityRequest: {
            /** Format: uuid */
            accountId: string;
            name: string;
            amount: number;
            /**
             * @description Starting stage on create (default PROSPECTING). On update it must be omitted or unchanged: stages change only through POST /opportunities/{id}/stage-transitions.
             * @enum {string}
             */
            stage?: "PROSPECTING" | "QUALIFICATION" | "PROPOSAL" | "NEGOTIATION" | "CLOSED_WON" | "CLOSED_LOST";
            /**
             * Format: int32
             * @description 0–100. Omit to use the stage's default. Closed stages are always 100 (won) or 0 (lost).
             */
            probability?: number;
            /** Format: date */
            closeDate: string;
            /** @enum {string} */
            type?: "NEW_BUSINESS" | "EXISTING_BUSINESS" | "RENEWAL" | "UPSELL";
            /** @enum {string} */
            leadSource?: "WEB" | "REFERRAL" | "EVENT" | "PARTNER" | "OUTBOUND" | "ADVERTISING" | "OTHER";
            description?: string;
            nextStep?: string;
            /**
             * Format: uuid
             * @description Owner; defaults to you on create and is unchanged on update when omitted.
             */
            ownerId?: string;
            /**
             * Format: int64
             * @description Required on update (optimistic locking).
             */
            version?: number;
        };
        AccountRefResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            type: "ENTERPRISE" | "SMB" | "STARTUP";
            archived: boolean;
        };
        OpportunityResponse: {
            /** Format: uuid */
            id: string;
            number: string;
            name: string;
            account: components["schemas"]["AccountRefResponse"];
            amount: number;
            /** @enum {string} */
            stage: "PROSPECTING" | "QUALIFICATION" | "PROPOSAL" | "NEGOTIATION" | "CLOSED_WON" | "CLOSED_LOST";
            /** Format: int32 */
            probability: number;
            weightedAmount: number;
            /** Format: date */
            closeDate: string;
            /** @enum {string} */
            type?: "NEW_BUSINESS" | "EXISTING_BUSINESS" | "RENEWAL" | "UPSELL";
            /** @enum {string} */
            leadSource?: "WEB" | "REFERRAL" | "EVENT" | "PARTNER" | "OUTBOUND" | "ADVERTISING" | "OTHER";
            description?: string;
            nextStep?: string;
            owner?: components["schemas"]["UserRefResponse"];
            /** Format: date-time */
            closedAt?: string;
            stageHistory: components["schemas"]["StageHistoryResponse"][];
            allowedStages: ("PROSPECTING" | "QUALIFICATION" | "PROPOSAL" | "NEGOTIATION" | "CLOSED_WON" | "CLOSED_LOST")[];
            archived: boolean;
            /** Format: date-time */
            archivedAt?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            version: number;
            permissions: components["schemas"]["RecordPermissions"];
        };
        RecordPermissions: {
            canEdit?: boolean;
            canArchive?: boolean;
        };
        StageHistoryResponse: {
            /** @enum {string} */
            fromStage?: "PROSPECTING" | "QUALIFICATION" | "PROPOSAL" | "NEGOTIATION" | "CLOSED_WON" | "CLOSED_LOST";
            /** @enum {string} */
            toStage: "PROSPECTING" | "QUALIFICATION" | "PROPOSAL" | "NEGOTIATION" | "CLOSED_WON" | "CLOSED_LOST";
            amount: number;
            /** Format: int32 */
            probability: number;
            changedBy?: components["schemas"]["UserRefResponse"];
            /** Format: date-time */
            changedAt: string;
        };
        UserRefResponse: {
            /** Format: uuid */
            id: string;
            fullName: string;
            active: boolean;
        };
        AddressDto: {
            street?: string;
            city?: string;
            state?: string;
            postalCode?: string;
            country?: string;
        };
        ContactRequest: {
            /** Format: uuid */
            accountId: string;
            firstName: string;
            lastName: string;
            /** Format: email */
            email?: string;
            phone?: string;
            title?: string;
            department?: string;
            /** @description Making a contact primary demotes the account's current primary contact. */
            primary?: boolean;
            mailingAddress?: components["schemas"]["AddressDto"];
            /**
             * Format: uuid
             * @description Owner; defaults to you on create and is unchanged on update when omitted.
             */
            ownerId?: string;
            /**
             * Format: int64
             * @description Required on update (optimistic locking).
             */
            version?: number;
        };
        ContactResponse: {
            /** Format: uuid */
            id: string;
            number: string;
            account: components["schemas"]["AccountRefResponse"];
            firstName: string;
            lastName: string;
            fullName: string;
            email?: string;
            phone?: string;
            title?: string;
            department?: string;
            primary: boolean;
            mailingAddress: components["schemas"]["AddressDto"];
            owner?: components["schemas"]["UserRefResponse"];
            archived: boolean;
            /** Format: date-time */
            archivedAt?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            version: number;
            permissions: components["schemas"]["RecordPermissions"];
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        AccountRequest: {
            /** @enum {string} */
            type: "ENTERPRISE" | "SMB" | "STARTUP";
            name: string;
            website?: string;
            phone?: string;
            industry?: string;
            /** Format: int32 */
            employeeCount?: number;
            annualRevenue?: number;
            billingAddress?: components["schemas"]["AddressDto"];
            shippingAddress?: components["schemas"]["AddressDto"];
            /**
             * Format: uuid
             * @description Owner; defaults to you on create and is unchanged on update when omitted.
             */
            ownerId?: string;
            enterprise?: components["schemas"]["EnterpriseProfile"];
            smb?: components["schemas"]["SmbProfile"];
            startup?: components["schemas"]["StartupProfile"];
            /**
             * Format: int64
             * @description Required on update (optimistic locking).
             */
            version?: number;
        };
        EnterpriseProfile: {
            enterpriseId?: string;
            /** Format: int32 */
            globalEmployeeCount?: number;
            subsidiaries?: string[];
            /** Format: uuid */
            accountManagerId?: string;
            hasEnterpriseSupport?: boolean;
        };
        SmbProfile: {
            businessType?: string;
            /** Format: int32 */
            yearsInBusiness?: number;
            ownerName?: string;
            localBusiness?: boolean;
        };
        StartupProfile: {
            /** @enum {string} */
            fundingRound?: "BOOTSTRAPPED" | "PRE_SEED" | "SEED" | "SERIES_A" | "SERIES_B" | "SERIES_C" | "SERIES_D_PLUS";
            totalFunding?: number;
            investorType?: string;
            /** Format: int32 */
            monthsToProfitability?: number;
            /** @enum {string} */
            growthStage?: "IDEA" | "MVP" | "EARLY_TRACTION" | "GROWTH" | "SCALE";
        };
        AccountResponse: {
            /** Format: uuid */
            id: string;
            number: string;
            /** @enum {string} */
            type: "ENTERPRISE" | "SMB" | "STARTUP";
            /** @enum {string} */
            tier: "STRATEGIC" | "MAJOR" | "ESTABLISHED" | "EMERGING" | "EARLY_STAGE" | "GROWTH_STAGE" | "LATE_STAGE";
            /** @enum {string} */
            supportLevel: "DEDICATED" | "PRIORITY" | "STANDARD";
            name: string;
            website?: string;
            phone?: string;
            industry?: string;
            /** Format: int32 */
            employeeCount?: number;
            annualRevenue?: number;
            billingAddress: components["schemas"]["AddressDto"];
            shippingAddress: components["schemas"]["AddressDto"];
            owner?: components["schemas"]["UserRefResponse"];
            enterprise?: components["schemas"]["EnterpriseProfile"];
            accountManager?: components["schemas"]["UserRefResponse"];
            smb?: components["schemas"]["SmbProfile"];
            startup?: components["schemas"]["StartupProfile"];
            archived: boolean;
            /** Format: date-time */
            archivedAt?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            version: number;
            permissions: components["schemas"]["RecordPermissions"];
        };
        CreateUserRequest: {
            /** Format: email */
            email: string;
            firstName: string;
            lastName: string;
            /** @enum {string} */
            role: "ADMIN" | "SALES_MANAGER" | "SALES_REP";
            password: string;
        };
        CreateSalesRepRequest: {
            /** Format: email */
            email: string;
            firstName: string;
            lastName: string;
            /**
             * @description SALES_REP or SALES_MANAGER
             * @enum {string}
             */
            role: "ADMIN" | "SALES_MANAGER" | "SALES_REP";
            password: string;
            title?: string;
            department?: string;
            phone?: string;
            territory?: string;
            quota?: number;
        };
        StageTransitionRequest: {
            /** @enum {string} */
            toStage: "PROSPECTING" | "QUALIFICATION" | "PROPOSAL" | "NEGOTIATION" | "CLOSED_WON" | "CLOSED_LOST";
            /**
             * Format: int64
             * @description The version you last loaded; a newer version on the server is a 409 CONFLICT.
             */
            version: number;
            /** @description Optional context, e.g. why the deal was lost. Shown on the timeline. */
            note?: string;
        };
        CreateLeadRequest: {
            firstName: string;
            lastName: string;
            company: string;
            /** Format: email */
            email: string;
            phone?: string;
            /** @enum {string} */
            source?: "WEB" | "REFERRAL" | "EVENT" | "PARTNER" | "OUTBOUND" | "ADVERTISING" | "OTHER";
            estimatedValue?: number;
            notes?: string;
            /**
             * Format: uuid
             * @description Owner; defaults to the signed-in user. Only managers and admins may assign to others.
             */
            ownerId?: string;
        };
        ConvertedRecordResponse: {
            /** Format: uuid */
            id: string;
            number: string;
            name: string;
        };
        LeadConversionSummaryResponse: {
            /** Format: date-time */
            convertedAt: string;
            account?: components["schemas"]["ConvertedRecordResponse"];
            contact?: components["schemas"]["ConvertedRecordResponse"];
            opportunity?: components["schemas"]["ConvertedRecordResponse"];
        };
        LeadResponse: {
            /** Format: uuid */
            id: string;
            number: string;
            firstName: string;
            lastName: string;
            fullName: string;
            company: string;
            email: string;
            phone?: string;
            /** @enum {string} */
            status: "NEW" | "CONTACTED" | "QUALIFIED" | "DISQUALIFIED" | "CONVERTED";
            /** @enum {string} */
            source?: "WEB" | "REFERRAL" | "EVENT" | "PARTNER" | "OUTBOUND" | "ADVERTISING" | "OTHER";
            estimatedValue?: number;
            notes?: string;
            owner?: components["schemas"]["OwnerResponse"];
            conversion?: components["schemas"]["LeadConversionSummaryResponse"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            version: number;
        };
        OwnerResponse: {
            /** Format: uuid */
            id: string;
            fullName: string;
            active: boolean;
        };
        LeadStatusTransitionRequest: {
            /**
             * @description NEW, CONTACTED, QUALIFIED or DISQUALIFIED. Leads become CONVERTED by conversion.
             * @enum {string}
             */
            status: "NEW" | "CONTACTED" | "QUALIFIED" | "DISQUALIFIED" | "CONVERTED";
            /**
             * Format: int64
             * @description The version you last loaded; a newer version on the server is a 409 CONFLICT.
             */
            version: number;
        };
        ConversionAccount: {
            /** @enum {string} */
            type: "ENTERPRISE" | "SMB" | "STARTUP";
            name: string;
            website?: string;
            phone?: string;
            industry?: string;
        };
        ConversionContact: {
            firstName: string;
            lastName: string;
            /** Format: email */
            email?: string;
            phone?: string;
            title?: string;
            /** @description Make the contact the account's primary contact (demotes the current one). */
            primary?: boolean;
        };
        ConversionOpportunity: {
            name: string;
            amount: number;
            /** Format: date */
            closeDate: string;
            /**
             * @description An open stage; defaults to PROSPECTING.
             * @enum {string}
             */
            stage?: "PROSPECTING" | "QUALIFICATION" | "PROPOSAL" | "NEGOTIATION" | "CLOSED_WON" | "CLOSED_LOST";
            /** @enum {string} */
            type?: "NEW_BUSINESS" | "EXISTING_BUSINESS" | "RENEWAL" | "UPSELL";
            nextStep?: string;
            description?: string;
        };
        LeadConversion: {
            /**
             * Format: int64
             * @description The lead version you reviewed; a newer version on the server is a 409 CONFLICT.
             */
            version: number;
            /**
             * Format: uuid
             * @description Attach the contact and opportunity to this active account instead of creating one.
             */
            existingAccountId?: string;
            /** @description The new account. Required unless existingAccountId is given. */
            account?: components["schemas"]["ConversionAccount"];
            contact: components["schemas"]["ConversionContact"];
            opportunity: components["schemas"]["ConversionOpportunity"];
            /**
             * Format: uuid
             * @description Owner of the new records; defaults to the lead's owner. Only managers and admins may choose someone else.
             */
            ownerId?: string;
        };
        LeadConversionResponse: {
            lead: components["schemas"]["LeadResponse"];
            account: components["schemas"]["ConvertedRecordResponse"];
            accountCreated: boolean;
            contact: components["schemas"]["ConvertedRecordResponse"];
            opportunity: components["schemas"]["ConvertedRecordResponse"];
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        MeResponse: {
            /** Format: uuid */
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            fullName: string;
            /** @enum {string} */
            role: "ADMIN" | "SALES_MANAGER" | "SALES_REP";
            permissions: components["schemas"]["PermissionsResponse"];
        };
        PermissionsResponse: {
            manageUsers: boolean;
            viewUsers: boolean;
            accessAllSalesRecords: boolean;
        };
        ActivityRequest: {
            /**
             * @description CALL, EMAIL, MEETING or NOTE. Other types are written by workflows only.
             * @enum {string}
             */
            type: "CALL" | "EMAIL" | "MEETING" | "NOTE" | "STAGE_CHANGE" | "LEAD_CONVERSION" | "ASSIGNMENT" | "RECORD_UPDATE";
            subject: string;
            body?: string;
            /**
             * Format: date-time
             * @description When it happened; defaults to now. Can't be in the future.
             */
            occurredAt?: string;
            /** Format: uuid */
            leadId?: string;
            /** Format: uuid */
            accountId?: string;
            /** Format: uuid */
            contactId?: string;
            /** Format: uuid */
            opportunityId?: string;
        };
        ActivityResponse: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "CALL" | "EMAIL" | "MEETING" | "NOTE" | "STAGE_CHANGE" | "LEAD_CONVERSION" | "ASSIGNMENT" | "RECORD_UPDATE";
            subject: string;
            body?: string;
            actor?: components["schemas"]["UserRefResponse"];
            /** Format: date-time */
            occurredAt: string;
            system: boolean;
            /** Format: uuid */
            leadId?: string;
            /** Format: uuid */
            accountId?: string;
            /** Format: uuid */
            contactId?: string;
            /** Format: uuid */
            opportunityId?: string;
        };
        PageResponseUserResponse: {
            content: components["schemas"]["UserResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        PageResponseSalesRepResponse: {
            content: components["schemas"]["SalesRepResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        PipelineCardResponse: {
            /** Format: uuid */
            id: string;
            number: string;
            name: string;
            account: components["schemas"]["AccountRefResponse"];
            amount: number;
            /** @enum {string} */
            stage: "PROSPECTING" | "QUALIFICATION" | "PROPOSAL" | "NEGOTIATION" | "CLOSED_WON" | "CLOSED_LOST";
            /** Format: int32 */
            probability: number;
            /** Format: date */
            closeDate: string;
            /** Format: date-time */
            closedAt?: string;
            nextStep?: string;
            owner?: components["schemas"]["UserRefResponse"];
            /** Format: int64 */
            version: number;
            allowedStages: ("PROSPECTING" | "QUALIFICATION" | "PROPOSAL" | "NEGOTIATION" | "CLOSED_WON" | "CLOSED_LOST")[];
        };
        PipelineColumnResponse: {
            /** @enum {string} */
            stage: "PROSPECTING" | "QUALIFICATION" | "PROPOSAL" | "NEGOTIATION" | "CLOSED_WON" | "CLOSED_LOST";
            /** Format: int64 */
            count: number;
            amount: number;
            weightedAmount: number;
            opportunities: components["schemas"]["PipelineCardResponse"][];
        };
        PipelineResponse: {
            columns: components["schemas"]["PipelineColumnResponse"][];
            totals: components["schemas"]["PipelineSummaryResponse"];
        };
        PipelineSummaryResponse: {
            /** Format: int64 */
            openCount: number;
            openAmount: number;
            weightedAmount: number;
            /** Format: int64 */
            wonCount: number;
            wonAmount: number;
            /** Format: int64 */
            lostCount: number;
        };
        OpportunitySummaryResponse: {
            /** Format: uuid */
            id: string;
            number: string;
            name: string;
            account: components["schemas"]["AccountRefResponse"];
            amount: number;
            /** @enum {string} */
            stage: "PROSPECTING" | "QUALIFICATION" | "PROPOSAL" | "NEGOTIATION" | "CLOSED_WON" | "CLOSED_LOST";
            /** Format: int32 */
            probability: number;
            /** Format: date */
            closeDate: string;
            owner?: components["schemas"]["UserRefResponse"];
            archived: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        PageResponseOpportunitySummaryResponse: {
            content: components["schemas"]["OpportunitySummaryResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        LeadSummaryResponse: {
            /** Format: uuid */
            id: string;
            number: string;
            fullName: string;
            company: string;
            email: string;
            /** @enum {string} */
            status: "NEW" | "CONTACTED" | "QUALIFIED" | "DISQUALIFIED" | "CONVERTED";
            /** @enum {string} */
            source?: "WEB" | "REFERRAL" | "EVENT" | "PARTNER" | "OUTBOUND" | "ADVERTISING" | "OTHER";
            estimatedValue?: number;
            owner?: components["schemas"]["OwnerResponse"];
            /** Format: date-time */
            createdAt: string;
        };
        PageResponseLeadSummaryResponse: {
            content: components["schemas"]["LeadSummaryResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        ContactSummaryResponse: {
            /** Format: uuid */
            id: string;
            number: string;
            fullName: string;
            email?: string;
            phone?: string;
            title?: string;
            primary: boolean;
            account: components["schemas"]["AccountRefResponse"];
            owner?: components["schemas"]["UserRefResponse"];
            archived: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        PageResponseContactSummaryResponse: {
            content: components["schemas"]["ContactSummaryResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        PageResponseActivityResponse: {
            content: components["schemas"]["ActivityResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        AccountSummaryResponse: {
            /** Format: uuid */
            id: string;
            number: string;
            name: string;
            /** @enum {string} */
            type: "ENTERPRISE" | "SMB" | "STARTUP";
            /** @enum {string} */
            tier: "STRATEGIC" | "MAJOR" | "ESTABLISHED" | "EMERGING" | "EARLY_STAGE" | "GROWTH_STAGE" | "LATE_STAGE";
            industry?: string;
            website?: string;
            /** Format: int32 */
            employeeCount?: number;
            annualRevenue?: number;
            owner?: components["schemas"]["UserRefResponse"];
            archived: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        PageResponseAccountSummaryResponse: {
            content: components["schemas"]["AccountSummaryResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesRepResponse"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SalesProfileRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesRepResponse"];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityResponse"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpportunityRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityResponse"];
                };
            };
        };
    };
    get_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactResponse"];
                };
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactResponse"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    update_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                q?: string;
                role?: "ADMIN" | "SALES_MANAGER" | "SALES_REP";
                active?: boolean;
                page?: number;
                size?: number;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseUserResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                q?: string;
                active?: boolean;
                page?: number;
                size?: number;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseSalesRepResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSalesRepRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesRepResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                /** @description Matches name or opportunity number */
                q?: string;
                stage?: ("PROSPECTING" | "QUALIFICATION" | "PROPOSAL" | "NEGOTIATION" | "CLOSED_WON" | "CLOSED_LOST")[];
                accountId?: string;
                /** @description Only this owner's opportunities. Reps may only pass their own id. */
                ownerId?: string;
                archived?: boolean;
                page?: number;
                size?: number;
                /** @description field[,asc|desc]; sortable: name, amount, probability, closeDate, createdAt, updatedAt, number */
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseOpportunitySummaryResponse"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpportunityRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityResponse"];
                };
            };
        };
    };
    transition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StageTransitionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityResponse"];
                };
            };
        };
    };
    restore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityResponse"];
                };
            };
        };
    };
    archive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityResponse"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: {
                /** @description Matches name, company, email or lead number */
                q?: string;
                status?: ("NEW" | "CONTACTED" | "QUALIFIED" | "DISQUALIFIED" | "CONVERTED")[];
                /** @description Only leads owned by this user. Reps may only pass their own id. */
                ownerId?: string;
                page?: number;
                size?: number;
                /** @description field[,asc|desc]; sortable: createdAt, updatedAt, lastName, company, status, estimatedValue, number */
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseLeadSummaryResponse"];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLeadRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadResponse"];
                };
            };
        };
    };
    changeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadStatusTransitionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadResponse"];
                };
            };
        };
    };
    convert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadConversion"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadConversionResponse"];
                };
            };
        };
    };
    list_4: {
        parameters: {
            query?: {
                /** @description Matches name, email, title or contact number */
                q?: string;
                accountId?: string;
                ownerId?: string;
                archived?: boolean;
                page?: number;
                size?: number;
                /** @description field[,asc|desc]; sortable: lastName, title, createdAt, updatedAt, number */
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseContactSummaryResponse"];
                };
            };
        };
    };
    create_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactResponse"];
                };
            };
        };
    };
    restore_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactResponse"];
                };
            };
        };
    };
    archive_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    timeline: {
        parameters: {
            query?: {
                leadId?: string;
                accountId?: string;
                contactId?: string;
                opportunityId?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseActivityResponse"];
                };
            };
        };
    };
    log: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityResponse"];
                };
            };
        };
    };
    list_5: {
        parameters: {
            query?: {
                /** @description Matches name, website, industry or account number */
                q?: string;
                type?: "ENTERPRISE" | "SMB" | "STARTUP";
                ownerId?: string;
                /** @description true lists archived accounts instead of active ones */
                archived?: boolean;
                page?: number;
                size?: number;
                /** @description field[,asc|desc]; sortable: name, industry, employeeCount, annualRevenue, createdAt, updatedAt, number */
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseAccountSummaryResponse"];
                };
            };
        };
    };
    create_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    restore_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    archive_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    board: {
        parameters: {
            query?: {
                /** @description Matches opportunity name or number */
                q?: string;
                accountId?: string;
                /** @description Only this owner's opportunities. Reps may only pass their own id. */
                ownerId?: string;
                /** @description Cards per column, 1–100 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineResponse"];
                };
            };
        };
    };
    stageHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageHistoryResponse"][];
                };
            };
        };
    };
    summary: {
        parameters: {
            query?: {
                accountId?: string;
                ownerId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineSummaryResponse"];
                };
            };
        };
    };
    get_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    csrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
