/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List leads
         * @description Paginated, searchable list of active (non-archived) leads.
         */
        get: operations["list"];
        put?: never;
        /** Create a lead */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a lead */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateLeadRequest: {
            firstName: string;
            lastName: string;
            company: string;
            /** Format: email */
            email: string;
            phone?: string;
            /** @enum {string} */
            source?: "WEB" | "REFERRAL" | "EVENT" | "PARTNER" | "OUTBOUND" | "ADVERTISING" | "OTHER";
            estimatedValue?: number;
            notes?: string;
        };
        LeadResponse: {
            /** Format: uuid */
            id: string;
            number: string;
            firstName: string;
            lastName: string;
            fullName: string;
            company: string;
            email: string;
            phone?: string;
            /** @enum {string} */
            status: "NEW" | "CONTACTED" | "QUALIFIED" | "DISQUALIFIED" | "CONVERTED";
            /** @enum {string} */
            source?: "WEB" | "REFERRAL" | "EVENT" | "PARTNER" | "OUTBOUND" | "ADVERTISING" | "OTHER";
            estimatedValue?: number;
            notes?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            version: number;
        };
        LeadSummaryResponse: {
            /** Format: uuid */
            id: string;
            number: string;
            fullName: string;
            company: string;
            email: string;
            /** @enum {string} */
            status: "NEW" | "CONTACTED" | "QUALIFIED" | "DISQUALIFIED" | "CONVERTED";
            /** @enum {string} */
            source?: "WEB" | "REFERRAL" | "EVENT" | "PARTNER" | "OUTBOUND" | "ADVERTISING" | "OTHER";
            estimatedValue?: number;
            /** Format: date-time */
            createdAt: string;
        };
        PageResponseLeadSummaryResponse: {
            content: components["schemas"]["LeadSummaryResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: {
                /** @description Matches name, company, email or lead number */
                q?: string;
                status?: ("NEW" | "CONTACTED" | "QUALIFIED" | "DISQUALIFIED" | "CONVERTED")[];
                page?: number;
                size?: number;
                /** @description field[,asc|desc]; sortable: createdAt, updatedAt, lastName, company, status, estimatedValue, number */
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseLeadSummaryResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLeadRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadResponse"];
                };
            };
        };
    };
}
