-- ParallaxCRM core relational model.
--
-- Conventions (see docs/architecture.md):
--   * uuid primary keys generated by the application; human-readable `number` from a sequence
--   * created_at / updated_at timestamptz, archived_at for soft archive, version for optimistic locking
--   * enumerations as varchar + CHECK; money as numeric(15,2)
--   * unique indexes are named uq_* so violations surface as DUPLICATE_RECORD errors

create extension if not exists pg_trgm;

-- ---------------------------------------------------------------------------
-- Identity & sales team
-- ---------------------------------------------------------------------------

create table users (
    id            uuid primary key,
    email         varchar(320) not null,
    password_hash varchar(100) not null,
    first_name    varchar(100) not null,
    last_name     varchar(100) not null,
    role          varchar(20)  not null,
    active        boolean      not null default true,
    last_login_at timestamptz,
    created_at    timestamptz  not null,
    updated_at    timestamptz  not null,
    version       bigint       not null default 0,
    constraint ck_users_role check (role in ('ADMIN', 'SALES_MANAGER', 'SALES_REP'))
);

create unique index uq_users_email on users (lower(email));

-- A sales rep is a user who carries a quota. YTD sales and attainment are derived from opportunities.
create table sales_reps (
    user_id    uuid primary key references users (id),
    title      varchar(120),
    department varchar(120),
    phone      varchar(40),
    territory  varchar(120),
    quota      numeric(15, 2) not null default 0,
    manager_id uuid references sales_reps (user_id),
    created_at timestamptz    not null,
    updated_at timestamptz    not null,
    version    bigint         not null default 0,
    constraint ck_sales_reps_quota check (quota >= 0),
    constraint ck_sales_reps_manager check (manager_id is null or manager_id <> user_id)
);

create index ix_sales_reps_manager on sales_reps (manager_id);

-- ---------------------------------------------------------------------------
-- Accounts (JOINED inheritance: accounts + one subtype table per account_type)
-- ---------------------------------------------------------------------------

create sequence account_number_seq;

create table accounts (
    id                   uuid primary key,
    number               varchar(20)    not null default ('ACC-' || lpad(nextval('account_number_seq')::text, 6, '0')),
    account_type         varchar(20)    not null,
    name                 varchar(200)   not null,
    website              varchar(255),
    phone                varchar(40),
    industry             varchar(100),
    employee_count       integer,
    annual_revenue       numeric(15, 2),
    billing_street       varchar(255),
    billing_city         varchar(120),
    billing_state        varchar(120),
    billing_postal_code  varchar(20),
    billing_country      varchar(120),
    shipping_street      varchar(255),
    shipping_city        varchar(120),
    shipping_state       varchar(120),
    shipping_postal_code varchar(20),
    shipping_country     varchar(120),
    owner_id             uuid references users (id),
    created_at           timestamptz    not null,
    updated_at           timestamptz    not null,
    archived_at          timestamptz,
    version              bigint         not null default 0,
    constraint uq_accounts_number unique (number),
    constraint ck_accounts_type check (account_type in ('ENTERPRISE', 'SMB', 'STARTUP')),
    constraint ck_accounts_employee_count check (employee_count is null or employee_count >= 0),
    constraint ck_accounts_annual_revenue check (annual_revenue is null or annual_revenue >= 0)
);

create unique index uq_accounts_name on accounts (lower(name)) where archived_at is null;
create index ix_accounts_owner on accounts (owner_id);
create index ix_accounts_name_trgm on accounts using gin (name gin_trgm_ops);

create table enterprise_accounts (
    account_id             uuid primary key references accounts (id) on delete cascade,
    enterprise_id          varchar(50),
    global_employee_count  integer,
    account_manager_id     uuid references users (id),
    has_enterprise_support boolean not null default false,
    constraint ck_enterprise_global_employees check (global_employee_count is null or global_employee_count >= 0)
);

create table enterprise_subsidiaries (
    id         uuid primary key,
    account_id uuid         not null references enterprise_accounts (account_id) on delete cascade,
    name       varchar(200) not null
);

create unique index uq_enterprise_subsidiaries_name on enterprise_subsidiaries (account_id, lower(name));

create table smb_accounts (
    account_id        uuid primary key references accounts (id) on delete cascade,
    business_type     varchar(100),
    years_in_business integer,
    owner_name        varchar(200),
    is_local_business boolean not null default false,
    constraint ck_smb_years check (years_in_business is null or years_in_business >= 0)
);

create table startup_accounts (
    account_id              uuid primary key references accounts (id) on delete cascade,
    funding_round           varchar(30),
    total_funding           numeric(15, 2),
    investor_type           varchar(50),
    months_to_profitability integer,
    growth_stage            varchar(30),
    constraint ck_startup_funding_round check (funding_round is null or funding_round in
        ('BOOTSTRAPPED', 'PRE_SEED', 'SEED', 'SERIES_A', 'SERIES_B', 'SERIES_C', 'SERIES_D_PLUS')),
    constraint ck_startup_total_funding check (total_funding is null or total_funding >= 0),
    constraint ck_startup_months check (months_to_profitability is null or months_to_profitability >= 0),
    constraint ck_startup_growth_stage check (growth_stage is null or growth_stage in
        ('IDEA', 'MVP', 'EARLY_TRACTION', 'GROWTH', 'SCALE'))
);

-- ---------------------------------------------------------------------------
-- Contacts
-- ---------------------------------------------------------------------------

create sequence contact_number_seq;

create table contacts (
    id                  uuid primary key,
    number              varchar(20)  not null default ('CON-' || lpad(nextval('contact_number_seq')::text, 6, '0')),
    account_id          uuid references accounts (id),
    first_name          varchar(100) not null,
    last_name           varchar(100) not null,
    email               varchar(320),
    phone               varchar(40),
    title               varchar(120),
    department          varchar(120),
    is_primary          boolean      not null default false,
    mailing_street      varchar(255),
    mailing_city        varchar(120),
    mailing_state       varchar(120),
    mailing_postal_code varchar(20),
    mailing_country     varchar(120),
    owner_id            uuid references users (id),
    created_at          timestamptz  not null,
    updated_at          timestamptz  not null,
    archived_at         timestamptz,
    version             bigint       not null default 0,
    constraint uq_contacts_number unique (number),
    constraint ck_contacts_primary_needs_account check (not is_primary or account_id is not null)
);

create unique index uq_contacts_email on contacts (lower(email)) where archived_at is null;
create unique index uq_contacts_primary_per_account on contacts (account_id) where is_primary and archived_at is null;
create index ix_contacts_account on contacts (account_id);
create index ix_contacts_owner on contacts (owner_id);
create index ix_contacts_name_trgm on contacts using gin ((first_name || ' ' || last_name) gin_trgm_ops);

-- ---------------------------------------------------------------------------
-- Opportunities & stage history
-- ---------------------------------------------------------------------------

create sequence opportunity_number_seq;

create table opportunities (
    id          uuid primary key,
    number      varchar(20)    not null default ('OPP-' || lpad(nextval('opportunity_number_seq')::text, 6, '0')),
    account_id  uuid           not null references accounts (id),
    name        varchar(200)   not null,
    stage       varchar(20)    not null,
    amount      numeric(15, 2) not null default 0,
    probability smallint       not null,
    close_date  date           not null,
    type        varchar(30),
    lead_source varchar(30),
    description text,
    next_step   varchar(255),
    owner_id    uuid references users (id),
    closed_at   timestamptz,
    created_at  timestamptz    not null,
    updated_at  timestamptz    not null,
    archived_at timestamptz,
    version     bigint         not null default 0,
    constraint uq_opportunities_number unique (number),
    constraint ck_opportunities_stage check (stage in
        ('PROSPECTING', 'QUALIFICATION', 'PROPOSAL', 'NEGOTIATION', 'CLOSED_WON', 'CLOSED_LOST')),
    constraint ck_opportunities_amount check (amount >= 0),
    constraint ck_opportunities_probability check (probability between 0 and 100),
    constraint ck_opportunities_type check (type is null or type in
        ('NEW_BUSINESS', 'EXISTING_BUSINESS', 'RENEWAL', 'UPSELL')),
    -- closed_at is set exactly when the opportunity is in a closed stage
    constraint ck_opportunities_closed check ((stage in ('CLOSED_WON', 'CLOSED_LOST')) = (closed_at is not null))
);

create index ix_opportunities_account on opportunities (account_id);
create index ix_opportunities_owner_stage on opportunities (owner_id, stage);
create index ix_opportunities_close_date on opportunities (close_date);
create index ix_opportunities_name_trgm on opportunities using gin (name gin_trgm_ops);

create table opportunity_stage_history (
    id             uuid primary key,
    opportunity_id uuid           not null references opportunities (id) on delete cascade,
    from_stage     varchar(20),
    to_stage       varchar(20)    not null,
    amount         numeric(15, 2) not null,
    probability    smallint       not null,
    changed_by     uuid references users (id),
    changed_at     timestamptz    not null
);

create index ix_stage_history_opportunity on opportunity_stage_history (opportunity_id, changed_at);

-- ---------------------------------------------------------------------------
-- Leads
-- ---------------------------------------------------------------------------

create sequence lead_number_seq;

create table leads (
    id                       uuid primary key,
    number                   varchar(20)    not null default ('LD-' || lpad(nextval('lead_number_seq')::text, 6, '0')),
    first_name               varchar(100)   not null,
    last_name                varchar(100)   not null,
    company                  varchar(200)   not null,
    email                    varchar(320)   not null,
    phone                    varchar(40),
    status                   varchar(20)    not null default 'NEW',
    source                   varchar(30),
    estimated_value          numeric(15, 2),
    notes                    text,
    owner_id                 uuid references users (id),
    converted_account_id     uuid references accounts (id),
    converted_contact_id     uuid references contacts (id),
    converted_opportunity_id uuid references opportunities (id),
    converted_at             timestamptz,
    created_at               timestamptz    not null,
    updated_at               timestamptz    not null,
    archived_at              timestamptz,
    version                  bigint         not null default 0,
    constraint uq_leads_number unique (number),
    constraint uq_leads_converted_contact unique (converted_contact_id),
    constraint uq_leads_converted_opportunity unique (converted_opportunity_id),
    constraint ck_leads_status check (status in ('NEW', 'CONTACTED', 'QUALIFIED', 'DISQUALIFIED', 'CONVERTED')),
    constraint ck_leads_source check (source is null or source in
        ('WEB', 'REFERRAL', 'EVENT', 'PARTNER', 'OUTBOUND', 'ADVERTISING', 'OTHER')),
    constraint ck_leads_estimated_value check (estimated_value is null or estimated_value >= 0),
    -- a converted lead always points at the account and contact it produced
    constraint ck_leads_conversion check ((status = 'CONVERTED') =
        (converted_at is not null and converted_account_id is not null and converted_contact_id is not null))
);

create unique index uq_leads_email on leads (lower(email)) where archived_at is null;
create index ix_leads_owner_status on leads (owner_id, status);
create index ix_leads_created_at on leads (created_at desc);
create index ix_leads_company_trgm on leads using gin (company gin_trgm_ops);
create index ix_leads_name_trgm on leads using gin ((first_name || ' ' || last_name) gin_trgm_ops);
create index ix_leads_email_trgm on leads using gin (email gin_trgm_ops);

-- ---------------------------------------------------------------------------
-- Activities (user-facing timeline) & audit events (immutable change log)
-- ---------------------------------------------------------------------------

create table activities (
    id             uuid primary key,
    type           varchar(30)  not null,
    subject        varchar(255) not null,
    body           text,
    actor_id       uuid references users (id),
    occurred_at    timestamptz  not null,
    lead_id        uuid references leads (id) on delete cascade,
    contact_id     uuid references contacts (id) on delete cascade,
    account_id     uuid references accounts (id) on delete cascade,
    opportunity_id uuid references opportunities (id) on delete cascade,
    created_at     timestamptz  not null,
    constraint ck_activities_type check (type in
        ('CALL', 'EMAIL', 'MEETING', 'NOTE', 'STAGE_CHANGE', 'LEAD_CONVERSION', 'ASSIGNMENT', 'RECORD_UPDATE')),
    constraint ck_activities_target check (num_nonnulls(lead_id, contact_id, account_id, opportunity_id) >= 1)
);

create index ix_activities_lead on activities (lead_id, occurred_at desc) where lead_id is not null;
create index ix_activities_contact on activities (contact_id, occurred_at desc) where contact_id is not null;
create index ix_activities_account on activities (account_id, occurred_at desc) where account_id is not null;
create index ix_activities_opportunity on activities (opportunity_id, occurred_at desc) where opportunity_id is not null;
create index ix_activities_occurred_at on activities (occurred_at desc);

create table audit_events (
    id          uuid primary key,
    entity_type varchar(40) not null,
    entity_id   uuid        not null,
    action      varchar(30) not null,
    actor_id    uuid references users (id),
    changes     jsonb       not null default '{}'::jsonb,
    occurred_at timestamptz not null,
    constraint ck_audit_events_action check (action in
        ('CREATE', 'UPDATE', 'ARCHIVE', 'RESTORE', 'DELETE', 'CONVERT', 'STAGE_CHANGE', 'ASSIGN'))
);

create index ix_audit_events_entity on audit_events (entity_type, entity_id, occurred_at desc);
create index ix_audit_events_occurred_at on audit_events (occurred_at desc);
